<!DOCTYPE html>
<html>
<head>
<title>Stock Scan: Candidates</title>

<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure-min.css" type="text/css">
<link rel="stylesheet" href="screen.css" type="text/css">

<script src="http://yui.yahooapis.com/3.10.3/build/yui/yui-min.js"></script>

</head>
<body class="yui3-skin-sam">

<div class="pure-g-r">
 <div class="splash pure-u-1">
   <div class="pure-g-r">
     <div class="pure-u-1-3">
       <div class="l-box splash-text">
         <h1 class="splash-head">psStockScreener</h1>
       </div>  
     </div>
     <div class="pure-u-2-3">
       <div class="l-box splash-text">
         <h2 class="splash-head">
